In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Everything works")

In [ ]:
!pip install numpy pandas matplotlib

In [ ]:
!pip install numpy pandas matplotlib

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Everything works")

Everything works


In [2]:
import numpy as np

numbers = np.arange(1, 11)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
random_matrix = np.random.randint(1, 10, size=(3, 3))
print(random_matrix)

[[3 4 6]
 [5 6 1]
 [9 7 1]]


In [4]:
print("Sum:", numbers.sum())
print("Mean:", numbers.mean())
print("Max:", numbers.max())

Sum: 55
Mean: 5.5
Max: 10


In [5]:
doubled_numbers = numbers * 2
print(doubled_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
filtered_numbers = numbers.copy()
filtered_numbers[filtered_numbers > 5] = 0
print(filtered_numbers)

[1 2 3 4 5 0 0 0 0 0]
